---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: precise64

suites:
- name: default
  run_list: ["recipe[base-box]"]
  attributes: {}
