name             'base-box'
maintainer       'Matt Rohrer'
maintainer_email 'matt@prognostikos.com'
license          'Apache 2.0'
description      'The basics for a server or workstation'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

supports 'ubuntu'

depends 'apt'
depends 'denyhosts'
depends 'git'
depends 'hostname'
depends 'firewall'
depends 'git'
depends 'mosh'
depends 'ntp'
depends 'openssh'
depends 'postfix'
depends 'resolver'
depends 'rsync'
depends 'sysstat'
depends 'sudo'
depends 'user'
